version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

  build_docker_image:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true # enable Docker layer caching for faster builds
      - run:
          name: Build_Image
          command: |
            TAG=0.1$CIRCLE_BUILD_NUM
            docker build -t djangotask -t shivaay025/djangotask:$TAG .
            echo $DOCKER_PASSWORD | docker login -u shivaay025 --password-stdin
            docker push shivaay025/djangotask:$TAG

workflows:
  build_and_deploy:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
          filters:
            branches:
              only: main
